//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblApartment()
        {
            this.tblContract = new HashSet<tblContract>();
            this.tblServiceBill = new HashSet<tblServiceBill>();
        }
    
        public int id { get; set; }
        public string apartId { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> area { get; set; }
        public string note { get; set; }
        public string image { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> familyId { get; set; }
    
        public virtual tblFamily tblFamily { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContract> tblContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceBill> tblServiceBill { get; set; }
    }
}
