//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContractDetail
    {
        public int contDetailId { get; set; }
        public string limitation { get; set; }
        public Nullable<System.DateTime> signDay { get; set; }
        public string content { get; set; }
        public Nullable<int> contractId { get; set; }
    
        public virtual tblContract tblContract { get; set; }
    }
}
