//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblContract = new HashSet<tblContract>();
            this.tblServiceBill = new HashSet<tblServiceBill>();
        }
    
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<bool> gender { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string email { get; set; }
        public string identityNumber { get; set; }
        public Nullable<int> departmentId { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContract> tblContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceBill> tblServiceBill { get; set; }
    }
}
