//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPerRelationship
    {
        public int idRel { get; set; }
        public Nullable<int> idUserRel { get; set; }
        public Nullable<int> idPerRel { get; set; }
    
        public virtual tblPermission tblPermission { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
